# Generated by Django 4.2 on 2023-04-03 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0002_rename_file_pdf_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf",
            name="time_of_upload",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
