# Generated by Django 4.2 on 2023-04-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0003_pdf_time_of_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf",
            name="number_of_pages",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pdf",
            name="parsing_status",
            field=models.CharField(
                choices=[
                    ("IN PROCESS", "IN PROCESS"),
                    ("DONE", "DONE"),
                    ("FAILED", "FAILED"),
                ],
                default="IN PROCESS",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="pdf",
            name="size",
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
