# Generated by Django 4.2 on 2023-04-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0005_alter_pdf_number_of_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdf",
            name="pdf_file",
            field=models.FileField(unique=True, upload_to=""),
        ),
    ]
