# Generated by Django 4.2 on 2023-04-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pdf", "0006_alter_pdf_pdf_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sentence", models.TextField()),
                (
                    "pdf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pdf.pdf"
                    ),
                ),
            ],
        ),
    ]
